-- one day... one day
return {}
-- return {
-- 	{
-- 		"mfussenegger/nvim-dap",
-- 		dependencies = {
-- 			"rcarriga/nvim-dap-ui",
-- 			"nvim-neotest/nvim-nio",
-- 			"theHamsta/nvim-dap-virtual-text",
-- 			"mfussenegger/nvim-dap-python",
-- 		},
-- 		keys = {
-- 			{
-- 				"<leader>db",
-- 				function()
-- 					require("dap").toggle_breakpoint()
-- 				end,
-- 				desc = "Toggle Breakpoint",
-- 			},
-- 			{
-- 				"<leader>dc",
-- 				function()
-- 					require("dap").continue()
-- 				end,
-- 				desc = "Continue",
-- 			},
-- 			{
-- 				"<leader>do",
-- 				function()
-- 					require("dap").step_over()
-- 				end,
-- 				desc = "Step Over",
-- 			},
-- 			{
-- 				"<leader>di",
-- 				function()
-- 					require("dap").step_into()
-- 				end,
-- 				desc = "Step Into",
-- 			},
-- 			{
-- 				"<leader>dO",
-- 				function()
-- 					require("dap").step_out()
-- 				end,
-- 				desc = "Step Out",
-- 			},
-- 			{
-- 				"<leader>dr",
-- 				function()
-- 					require("dap").repl.toggle()
-- 				end,
-- 				desc = "Toggle REPL",
-- 			},
-- 			{
-- 				"<leader>du",
-- 				function()
-- 					require("dapui").toggle()
-- 				end,
-- 				desc = "Toggle DAP UI",
-- 			},
-- 		},
-- 		config = function()
-- 			local dap = require("dap")
-- 			local dapui = require("dapui")
--
-- 			dapui.setup()
-- 			require("nvim-dap-virtual-text").setup()
--
-- 			-- Auto open/close the UI panels on session events
-- 			dap.listeners.after.event_initialized["dapui_config"] = function()
-- 				dapui.open()
-- 			end
-- 			dap.listeners.before.event_terminated["dapui_config"] = function()
-- 				dapui.close()
-- 			end
-- 			dap.listeners.before.event_exited["dapui_config"] = function()
-- 				dapui.close()
-- 			end
--
-- 			-- GDB adapter (C/C++/Rust) — requires gdb 14.0+
-- 			dap.adapters.gdb = {
-- 				type = "executable",
-- 				command = "gdb",
-- 				args = { "--interpreter=dap", "--eval-command", "set print pretty on" },
-- 			}
--
-- 			dap.configurations.c = {
-- 				{
-- 					name = "Launch",
-- 					type = "gdb",
-- 					request = "launch",
-- 					program = function()
-- 						return vim.fn.input("Path to executable: ", vim.fn.getcwd() .. "/", "file")
-- 					end,
-- 					args = {},
-- 					cwd = "${workspaceFolder}",
-- 					stopAtBeginningOfMainSubprogram = false,
-- 				},
-- 				{
-- 					name = "Select and attach to process",
-- 					type = "gdb",
-- 					request = "attach",
-- 					program = function()
-- 						return vim.fn.input("Path to executable: ", vim.fn.getcwd() .. "/", "file")
-- 					end,
-- 					pid = function()
-- 						local name = vim.fn.input("Executable name (filter): ")
-- 						return require("dap.utils").pick_process({ filter = name })
-- 					end,
-- 					cwd = "${workspaceFolder}",
-- 				},
-- 				{
-- 					name = "Attach to gdbserver :1234",
-- 					type = "gdb",
-- 					request = "attach",
-- 					target = "localhost:1234",
-- 					program = function()
-- 						return vim.fn.input("Path to executable: ", vim.fn.getcwd() .. "/", "file")
-- 					end,
-- 					cwd = "${workspaceFolder}",
-- 				},
-- 			}
--
-- 			dap.configurations.cpp = dap.configurations.c
-- 			dap.configurations.rust = dap.configurations.c
--
-- 			-- Python via debugpy
-- 			require("dap-python").setup("python3")
-- 		end,
-- 	},
-- }
