local keymap = vim.keymap.set

keymap("v", "<C-c>", '"+y', { noremap = true, silent = true, desc = "Copy to system clipboard" })
keymap("i", "<C-r>", '<C-r>"', { noremap = true, silent = true, desc = "Paste from register" })
keymap({ "v", "o" }, "00", "$", { noremap = true, desc = "Go to end of line" })
keymap("n", "<Esc>", "<cmd>nohlsearch<CR>", { noremap = true, silent = true, desc = "Turn off the highlight" })
keymap("n", "<leader>e", "<cmd>Oil<CR>", { desc = "Open Oil file explorer" })
keymap("n", "<leader>z", "z=1<CR><CR>", { desc = "Auto correct 4 me" })
keymap("n", "<M-p>", "<cmd>vs<CR>", { desc = "Open Terminal" })
keymap("n", "<M-i>", "<cmd>split><CR>", { desc = "Open Terminal" })
keymap("t", "<Esc>", [[<C-\><C-n>]], { noremap = true, silent = true, desc = "Exit terminal mode" })
keymap("n", "<A-Up>", ":resize +5<CR>", { noremap = true, desc = "Increase window height" })
keymap("n", "<A-Down>", ":resize -5<CR>", { noremap = true, desc = "Decrease window height" })
keymap("n", "<A-Left>", ":vertical resize -5<CR>", { noremap = true, desc = "Decrease window width" })
keymap("n", "<A-Right>", ":vertical resize +5<CR>", { noremap = true, desc = "Increase window width" })
keymap("n", "<A-Tab>", "<C-w>w", { noremap = true, desc = "Switch to next window" })
keymap("n", "<C-q><leader>", "<cmd>copen<CR>", { desc = "Open the quick fix list" })
keymap("n", "<C-q>j", "<cmd>cnext<CR>", { desc = "Open the quick fix list" })
keymap("n", "<C-q>k", "<cmd>cprevious<CR>", { desc = "Open the quick fix list" })
keymap("n", "<leader>k", "<cmd>cd %:p:h <CR>", { desc = "Update the working directory" })
keymap("i", "<C-p>", "<Esc>pi", { noremap = true, silent = true })

keymap({ "n", "v" }, ";", ":", { desc = "Enter command mode" })
keymap({ "n", "v" }, ":", ";", { desc = "Repeat last f/t motion" })
keymap("n", "<leader>o", ":Z ", { noremap = true })
-- keymap("i", "<C-d>", "<C-o>x", { noremap = true })
keymap("i", "<C-e>", "<C-o>$", { noremap = true })
keymap("i", "<C-a>", "<C-o>0", { noremap = true })
keymap("i", "<C-k>", "<C-o>D", { noremap = true })
keymap("i", "<C-u>", "<C-o>d^", { noremap = true })
keymap("i", "<C-o>", "<C-o>O", { noremap = true, desc = "Open line below" })
keymap("i", "<C-O>", "<C-o>o", { noremap = true })
keymap("i", "<C-k>", "<C-o>w", { noremap = true })
keymap("i", "<C-j>", "<C-o>b", { noremap = true })
keymap("i", "<C-d>", "<C-o>x", { noremap = true, silent = true })
keymap("i", "<C-s>", "<Esc>ediwi", { noremap = true, silent = true })
