local keymap = vim.keymap.set

keymap("v", "<C-c>", '"+y', { noremap = true, silent = true, desc = "Copy to system clipboard" })
keymap("i", "<C-r>", '<C-r>"', { noremap = true, silent = true, desc = "Paste from register" })
keymap({ "v", "o" }, "00", "$", { noremap = true, desc = "Go to end of line" })
keymap("n", "<Esc>", "<cmd>nohlsearch<CR>", { noremap = true, silent = true, desc = "Turn off the highlight" })
keymap("n", "<leader>e", "<cmd>Oil<CR>", { desc = "Open Oil file explorer" })
keymap({ "n", "v", "x" }, ":", ";", { desc = "Revamp of the century" })
keymap({ "n", "v", "x" }, ";", ":", { desc = "Revamp of the century" })
keymap("n", "<leader>z", "z=1<CR><CR>", { desc = "Auto correct 4 me" })
keymap("n", "<M-p>", "<cmd>vs<CR>", { desc = "Open Terminal" })
keymap("n", "<M-i>", "<cmd>split><CR>", { desc = "Open Terminal" })
keymap("t", "<Esc>", [[<C-\><C-n>]], { noremap = true, silent = true, desc = "Exit terminal mode" })
keymap("n", "<A-Up>", ":resize +5<CR>", { noremap = true, desc = "Increase window height" })
keymap("n", "<A-Down>", ":resize -5<CR>", { noremap = true, desc = "Decrease window height" })
keymap("n", "<A-Left>", ":vertical resize -5<CR>", { noremap = true, desc = "Decrease window width" })
keymap("n", "<A-Right>", ":vertical resize +5<CR>", { noremap = true, desc = "Increase window width" })
keymap("n", "<A-Tab>", "<C-w>w", { noremap = true, desc = "Switch to next window" })
keymap("n", "<leader>=", "<C-w>=")
keymap("n", "<C-q><leader>", "<cmd>copen<CR>", { desc = "Open the quick fix list" })
keymap("n", "<C-q>j", "<cmd>cnext<CR>", { desc = "Open the quick fix list" })
keymap("n", "<C-q>k", "<cmd>cprevious<CR>", { desc = "Open the quick fix list" })
keymap("n", "<leader>k", "<cmd>cd %:p:h <CR>", { desc = "Update the working directory" })
keymap("i", "<C-p>", "<Esc>pi", { noremap = true, silent = true })
